name: yaml_writer
description: A library to write YAML documents, supporting Object encoding and 'dart:convert' 'Converter'.
version: 2.0.1
homepage: https://github.com/gmpassos/yaml_writer

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.8
  dependency_validator: ^3.2.3
  coverage: ^1.10.0
