name: yaml_writer
description: A library to write YAML documents, supporting Object encoding and 'dart:convert' 'Converter'.
version: 2.1.0
homepage: https://github.com/gmpassos/yaml_writer

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  dependency_validator: ^5.0.2
  coverage: ^1.11.1
  yaml: ^3.1.3
